using System;
using System.Collections.Generic;

namespace Model
{
    public partial class Articles:IPermission
    {
        public Articles()
        {
            Comments = new HashSet<Comments>();
        }

        [HideColumnIfAutoGenerated()]
        public int Id { get; set; }
        public string ShortName { get; set; }
        //[HideColumnIfAutoGenerated()]
        public string Decription { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime LastChange { get; set; }
        [HideColumnIfAutoGenerated()]
        public int? AuthorId { get; set; }
        [HideColumnIfAutoGenerated()]
        public int? DocumentTypeId { get; set; }
        public int? SecurityLabel { get; set; }

        [HideColumnIfAutoGenerated()]
        public virtual Authors Author { get; set; }
        [HideColumnIfAutoGenerated()]
        public virtual DocumentTypes DocumentType { get; set; }
        [HideColumnIfAutoGenerated()]
        public virtual SecurityLabels SecurityLabelNavigation { get; set; }
        [HideColumnIfAutoGenerated()]
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
