using System;
using System.Collections.Generic;

namespace Model
{
    public partial class Comments: IPermission
    {
        [HideColumnIfAutoGenerated()]
        public int Id { get; set; }
        public int? AuthorId { get; set; }
        public int? ArticleId { get; set; }
        public string Body { get; set; }
        public int? SecurityLabel { get; set; }

        [HideColumnIfAutoGenerated()]
        public virtual Articles Article { get; set; }
        [HideColumnIfAutoGenerated()]
        public virtual Authors Author { get; set; }
        [HideColumnIfAutoGenerated()]
        public virtual SecurityLabels SecurityLabelNavigation { get; set; }
    }
}
