using System;
using System.Collections.Generic;

namespace Model
{
    public partial class DocumentTypes:IPermission
    {
        public DocumentTypes()
        {
            Articles = new HashSet<Articles>();
        }

        [HideColumnIfAutoGenerated()]
        public int Id { get; set; }
        public string Type { get; set; }
        public int? SecurityLabel { get; set; }

        public override string ToString()
        {
            return Type;
        }

        [HideColumnIfAutoGenerated()]
        public virtual SecurityLabels SecurityLabelNavigation { get; set; }
        [HideColumnIfAutoGenerated()]
        public virtual ICollection<Articles> Articles { get; set; }
    }
}
